# Generated by Django 4.2.1 on 2023-07-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('category', models.CharField(null=True, blank=True, max_length=20)),
                ('image', models.ImageField(null=True, blank=True, upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='bids',
            new_name='bid',
        ),
        migrations.RenameModel(
            old_name='comments',
            new_name='comment',
        ),
        migrations.DeleteModel(
            name='listings',
        ),
    ]
