# Generated by Django 4.2.1 on 2023-07-07 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='Watchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
