# Generated by Django 4.2.1 on 2023-07-08 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_comment_commented_alter_comment_commenter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='prevbid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bid',
            name='prevbuyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prevbuyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
