# Generated by Django 4.2.1 on 2023-07-10 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_listing_posted_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='posted_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
